### ISSUE TITLE
Consider adding an .nvmrc file to the repo

### ISSUE THREAD

**Issue by omarkohl** [cleodora-forecasting/cleodora#132]
https://davidwalsh.name/nvmrc

It could then be used by the setup-node action in the workflows to ensure everywhere the same node.js version is used.

```yaml
- uses: actions/setup-node@v2
  with:
    node-version-file: '.nvmrc'
```
