### ISSUE TITLE
Goreleaser: Rename archives so the target platform name is more user friendly

### ISSUE THREAD

**Issue by omarkohl** [cleodora-forecasting/cleodora#167]
```yaml
archives:
- 
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
```

Found here https://github.com/magefile/mage/blob/a9206042d42a592ddc649a2e42e5007cfad59b01/.goreleaser.yml
